import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import { useAuthState, useSignInWithGoogle } from 'react-firebase-hooks/auth'
import { auth } from '../firebase/clientApp'
import Loading from '../components/Loading'
import { useRouter } from 'next/navigation'

export default function Home() {
  const [ user, loading, error ] = useAuthState(auth);
  const router = useRouter();

  if(error) {
    console.log(error);
    return (
      <Text>Fuck error</Text>
    )
  }

  if(loading){
    return (
      <Loading />
    )
  }

  if(!user) {
    router.push('/login');
    return null;
  }

  if(user) {
    router.push('/homepage');
    return null;
  }

  return (
    <div>
      <Head>
        <title>Headache Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}