import { Text } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/navigation';
import { useAuthState } from 'react-firebase-hooks/auth';
import Loading from '../components/Loading';
import { auth } from '../firebase/clientApp';

export default function Home() {
  const [user, loading, error] = useAuthState(auth);
  const router = useRouter();
  // If login fails, display error
  if (error) {
    console.log(error);
    return <Text>Fuck error</Text>;
  }
  // If loading, display loading screen
  if (loading) {
    return <Loading />;
  }
  // If user is not logged in, redirect to login page
  if (!user) {
    router.push('/login');
    return null;
  }
  // If user is logged in, redirect to homepage
  if (user) {
    router.push('/homepage');
    return null;
  }

  return (
    <div>
      <Head>
        <title>Headache Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
